// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-bVwRzVlDwyLcqNRhcRXPsZk5vLTLt4',
    appId: '1:54461003846:web:89da249cdb2d61be3b3247',
    messagingSenderId: '54461003846',
    projectId: 'ecoflow-9c7d4',
    authDomain: 'ecoflow-9c7d4.firebaseapp.com',
    databaseURL: 'https://ecoflow-9c7d4-default-rtdb.firebaseio.com',
    storageBucket: 'ecoflow-9c7d4.firebasestorage.app',
    measurementId: 'G-YJ5R15T3S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA90OLNN2bE-hTwCmfaGe71iSgobQ8Td74',
    appId: '1:54461003846:android:e52f575cac8c842f3b3247',
    messagingSenderId: '54461003846',
    projectId: 'ecoflow-9c7d4',
    databaseURL: 'https://ecoflow-9c7d4-default-rtdb.firebaseio.com',
    storageBucket: 'ecoflow-9c7d4.firebasestorage.app',
  );
}
